# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Stakeholder.create(name: 'Alison Eckhardt', title: "CIO", alias: 'R2D2')
# Stakeholder.create(name: 'Eric Prydz', title: "Sponsor", alias: 'C3P0')
# Stakeholder.create(name: 'Nicola Green', title: "Programme Manager", alias: 'Ponder')
# Stakeholder.create(name: 'Sue Lorenzo', title: "Head of Customer Service", alias: 'Curious')
# Stakeholder.create(name: 'Harry Lancaster', title: "HR Manager", alias: 'Mellow')
# Stakeholder.create(name: 'Simone Esther', title: "Head of Operations", alias: 'Cycle')
# Stakeholder.create(name: 'Peter Morris', title: "Sales Manager", alias: 'Disruption')
# Stakeholder.create(name: 'Betty Roland', title: "Finance Manager", alias: 'Waving')
# Stakeholder.create(name: 'Richard Lockhart', title: "Digital Expert", alias: 'Interested')
# Stakeholder.create(name: 'Fran Andersson', title: "eBusiness Manager", alias: 'Direct')
# Stakeholder.create(name: 'Zoe Sole', title: "Head of Communications", alias: 'Positivity')
# Stakeholder.create(name: 'Matthew Amber', title: "Head of HR", alias: 'Negative')
# Stakeholder.create(name: 'Louise Thompson', title: "Marketing Manager", alias: 'Extrovert')
# Stakeholder.create(name: 'Mayowa Stiller', title: "IS Project Manager", alias: 'Running')
# Stakeholder.create(name: 'Connie Morris', title: "Digital Comms Expert", alias: 'Slow')
# Stakeholder.create(name: 'Adam Smith', title: "ERP Systems Manager", alias: 'Happy')
# Stakeholder.create(name: 'Marie Larsson', title: "CRM Manager", alias: 'Sad')

# Rating.create(stakeholder_id: 1, power: 5, interest: 6, positivity: 1)
# Rating.create(stakeholder_id: 2, power: 2, interest: 3, positivity: 4)
# Rating.create(stakeholder_id: 3, power: 9, interest: 6, positivity: 10)
# Rating.create(stakeholder_id: 4, power: 1, interest: 10, positivity: 3)
# Rating.create(stakeholder_id: 5, power: 10, interest: 4, positivity: 2)
# Rating.create(stakeholder_id: 6, power: 7, interest: 3, positivity: 8)
# Rating.create(stakeholder_id: 7, power: 5, interest: 2, positivity: 9)
# Rating.create(stakeholder_id: 8, power: 6, interest: 8, positivity: 7)
# Rating.create(stakeholder_id: 9, power: 2, interest: 7, positivity: 8)
# Rating.create(stakeholder_id: 10, power: 8, interest: 2, positivity: 3)
# Rating.create(stakeholder_id: 11, power: 5, interest: 4, positivity: 5)
# Rating.create(stakeholder_id: 12, power: 9, interest: 5, positivity: 5)
# Rating.create(stakeholder_id: 13, power: 4, interest: 9, positivity: 4)
# Rating.create(stakeholder_id: 14, power: 3, interest: 2, positivity: 8)
# Rating.create(stakeholder_id: 15, power: 8, interest: 6, positivity: 6)
# Rating.create(stakeholder_id: 16, power: 2, interest: 7, positivity: 2)
# Rating.create(stakeholder_id: 17, power: 10, interest: 3, positivity: 4)

Project.create(name: "Digital Transformation", description: "Integrating all social, web, mobile, ecommerce, service efforts and investments to deliver an integrated and frictionless customer experience.")
Project.create(name: "Data Analytics for Project Management", description: "Develop and implement tools to analyse project data.")
